#!/bin/bash

proxy_rc_file=$(grep 'export http_proxy=' ~/.zshrc | awk -F'[/:]' '{print $4}')
proxy_wsl=$(cat /etc/resolv.conf | grep nameserver | awk '{ print $2 }')

if [[ ${proxy_wsl} != ${proxy_rc_file} ]];then

    sed -i "s/${proxy_rc_file}/${proxy_wsl}/g" ~/.zshrc
    echo "the proxy ip in ~/.zshrc file is: ${proxy_rc_file}"
    echo "the proxy ip in wsl2 is: ${proxy_wsl}"
    echo "wsl proxy is updated!"

else

    echo "the proxy ip in ~/.zshrc file and wsl2 are same, is: ${proxy_rc_file}."
    echo "It's no need to update!"

fi
