#!/bin/bash

set -e

script_name=$(basename "$0")

help() {
  echo "Upload files to remote server using rsync."
  echo -e "\nUsage:"
  echo "   ${script_name} [SERVER_ALIAS] [FILES...]"
  exit 1
}

if [ "$#" -lt 2 ]; then
  help
fi

SERVER_ALIAS=$1
shift

if [ "$SERVER_ALIAS" = "Master" ]; then
  REMOTE_PATH="~/sync"
else
  REMOTE_PATH="~/yangsl/sync"
fi

rsync -avuP --human-readable "$@" "$SERVER_ALIAS:$REMOTE_PATH"

echo -e "\nUpload completed."
